
// export const GET_ALL_RESTAURANTS = 'GET_ALL_RESTAURANTS';
// export const GET_RESTAURANT_BY_NAME = 'GET_RESTAURANT_BY_NAME';

export const GET_ALL_USER = 'GET_ALL_USERS';
export const GET_USER = 'GET_USER';

export const GET_USER_LOCATION = 'GET_USER_LOCATION';

export const CHECK_USER_LOGIN = 'CHECK_USER_LOGIN';
export const GET_RESTAURANT_DATA = 'GET_RESTAURANT_DATA';
export const SET_CATEGORIES = 'SET_CATEGORIES';