
export const GET_ALL_RESTAURANTS = 'GET_ALL_RESTAURANTS';
export const GET_RESTAURANT_BY_NAME = 'GET_RESTAURANT_BY_NAME';


export const GET_ALL_USER = 'GET_ALL_USERS';
export const GET_USER = 'GET_USER';



export const GET_LOCATION = 'GET_LOCATION';